### ISSUE TITLE
Cheat Engine Table?

### ISSUE THREAD

**Issue by GD-NTB** [MCJack123/DashBot-3.0#11]
Not sure if you used Cheat Engine to find the static addresses for the current game mode and for jumping (e.g. line 23 in dashbot.cpp), but if you did, is it possible you could reply with the table? It would be a massive help for the project I'm currently working on - a GD AI using the NEAT algorithm and neural networks.

(Not sure if this is the correct place to ask this)

**Comment by MCJack123** [comment]
I've documented my findings in the Geometry Dash memory here: https://gist.github.com/MCJack123/ed00353622d562f09ccc34402a33ea6a
