### ISSUE TITLE
Unable to Locate dashbot.exe file

### ISSUE THREAD

**Issue by EdgeSloth** [MCJack123/DashBot-3.0#5]
I've downloaded the latest release but the dashbot.exe is not there.

**Comment by MCJack123** [comment]
https://github.com/MCJack123/DashBot-3.0/releases/download/3.0.1/dashbot.exe

**Comment by MCJack123** [comment]
If the file's disappearing when you run it, it was probably quarantined by your anti-virus. Make sure your anti-virus has an exception set for the file.
